kind: pipeline
name: default

services:
- name: database
  image: mysql:5.7
  ports:
    - 3306
  environment:
    MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'

- name: rabbitmq
  image: rabbitmq:3.7.6-management
  ports:
    - 5672

- name: redis
  image: redis:4.0
  ports:
    - 6379

steps:
# Copy bundler cache from the host machine to your build environment.
# Plugin description: http://plugins.drone.io/drillster/drone-volume-cache
- name: restore-bundler-cache
  pull: default
  image: drillster/drone-volume-cache
  settings:
    restore: true
    mount:
    - vendor/bundle
  volumes:
  - name: bundle-cache
    path: /cache

# Copy docker cache from the host machine to your build environment.
# Plugin description: http://plugins.drone.io/drillster/drone-volume-cache
- name: restore-docker-cache
  pull: default
  image: drillster/drone-volume-cache
  settings:
    restore: true
    mount:
    - /var/lib/docker
  volumes:
  - name: docker-cache
    path: /cache

# Wait MySQL to be ready for taking connections.
- name: wait-for-mysql
  image: jwilder/dockerize
  commands:
  - dockerize -wait tcp://database:3306 -timeout 1m

# Initialize application. Install dependencies. Migrate database. Run rspec.
- name: run-rspec
  image: ruby:2.5.3
  environment:
    DATABASE_HOST: database
    RABBITMQ_HOST: rabbitmq
    EVENT_API_RABBITMQ_HOST: rabbitmq
    REDIS_URL: redis://redis:6379
    RAILS_ENV: test
  commands:
  - ./bin/init_config
  - bundle install --deployment --without production development --jobs=$(nproc) --retry=3
  - bundle exec rake db:create db:migrate
  - LOG_LEVEL=warn bundle exec rspec

# Copy bundler cache from the build environment to your host machine.
# Plugin description: http://plugins.drone.io/drillster/drone-volume-cache
- name: rebuild-bundler-cache
  pull: default
  image: drillster/drone-volume-cache
  settings:
    rebuild: true
    mount:
    - vendor/bundle
  volumes:
  - name: bundle-cache
    path: /cache

# Update application version, markdown and swagger documentation, then push it to git repository.
- name: git-tag-and-push
  image: ruby:2.5.3
  settings:
    github_api_key:
      from_secret: github_api_key
  commands:
  - rake release:drone
  - echo "latest,$DRONE_BRANCH,$(git describe --tags --abbrev=0)" > .tags
  - cat .tags
  trigger:
    event:
    - push
    branch:
    - 2-0/issue-1903

# Build and push docker image using ".tags" file.
- name: docker-build-and-push
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: rubykube/peatio
  trigger:
    event:
    - push
    branch:
    - 2-0/issue-1903

# Copy docker cache from the build environment to your host machine.
# Plugin description: http://plugins.drone.io/drillster/drone-volume-cache
- name: rebuild-docker-cache
  pull: default
  image: drillster/drone-volume-cache
  settings:
    rebuild: true
    mount:
    - vendor/bundle
  volumes:
  - name: bundle-cache
    path: /cache
  trigger:
    event:
    - push
    branch:
    - 2-0/issue-1903

volumes:
- name: bundler-cache
  host:
    path: /tmp/
- name: docker-cache
  host:
    path: /tmp/
